# 📌 Analisis Sentimen Masyarakat terhadap Proyek Transportasi Modern di Indonesia melalui Komentar YouTube


## 1. Business Understanding
### Latar Belakang

Infrastruktur transportasi modern seperti Kereta Cepat Whoosh, MRT Jakarta, dan LRT Jabodebek merupakan bagian dari transformasi sistem transportasi nasional. Kehadiran proyek-proyek tersebut memunculkan berbagai respons dari masyarakat yang dapat diamati melalui media sosial, salah satunya YouTube.

Komentar pengguna YouTube mengandung opini, pengalaman, serta persepsi masyarakat terhadap kualitas layanan, manfaat ekonomi, kenyamanan, hingga efektivitas pembangunan transportasi modern.

Analisis sentimen dapat digunakan untuk mengidentifikasi kecenderungan opini masyarakat secara otomatis menggunakan teknik Natural Language Processing (NLP).

### Tujuan
1. Mengumpulkan komentar publik dari YouTube.
2. Mengklasifikasikan sentimen menjadi positif, netral, dan negatif.
3. Membangun model machine learning dan deep learning.
4. Membandingkan performa beberapa algoritma.

## 2. Import Library

### Tujuan

Menginstal library yang diperlukan untuk scraping data.

In [ ]:
!pip install google-api-python-client pandas tqdm

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.196.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.47.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.4.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.30.3)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.28.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.20.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.5.20)

In [ ]:
!pip install pipreqs

Requirement already satisfied: pipreqs in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: docopt==0.6.2 in /usr/local/lib/python3.12/dist-packages (from pipreqs) (0.6.2)
Requirement already satisfied: ipython==8.12.3 in /usr/local/lib/python3.12/dist-packages (from pipreqs) (8.12.3)
Requirement already satisfied: nbconvert<8.0.0,>=7.11.0 in /usr/local/lib/python3.12/dist-packages (from pipreqs) (7.17.1)
Requirement already satisfied: yarg==0.1.9 in /usr/local/lib/python3.12/dist-packages (from pipreqs) (0.1.9)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (4.4.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (0.20.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (0.2.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (2.20.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (0.6.3)
Requirement already satisfied: traitlets>=5 in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython==8.12.3->pipreqs) (4.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from yarg==0.1.9->pipreqs) (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (5.9.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (3.2.1)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (0.10.4)
Requirement already satisfied: nbformat>=5.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (5.10.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (26.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert<8.0.0,>=7.11.0->pipreqs) (1.5.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (1.4.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython==8.12.3->pipreqs) (0.8.7)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (4.9.6)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (7.4.9)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (4.26.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython==8.12.3->pipreqs) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython==8.12.3->pipreqs) (0.7.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert<8.0.0,>=7.11.0->pipreqs) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert<8.0.0,>=7.11.0->pipreqs) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->yarg==0.1.9->pipreqs) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->yarg==0.1.9->pipreqs) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->yarg==0.1.9->pipreqs) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->yarg==0.1.9->pipreqs) (2026.5.20)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from stack-data->ipython==8.12.3->pipreqs) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from stack-data->ipython==8.12.3->pipreqs) (3.0.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.12/dist-packages (from stack-data->ipython==8.12.3->pipreqs) (0.2.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert<8.0.0,>=7.11.0->pipreqs) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (0.4)
Requirement already satisfied: nest-asyncio>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (2.9.0.post0)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (26.2.1)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (6.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert<8.0.0,>=7.11.0->pipreqs) (1.17.0)

In [ ]:
!pip freeze > requirements.txt

## 3. Koneksi ke YouTube Data API
### Tujuan

Menghubungkan notebook dengan YouTube Data API v3 agar dapat melakukan pencarian video dan pengambilan komentar.

## Import Library

In [ ]:
import pandas as pd
from tqdm import tqdm
from googleapiclient.discovery import build

## Koneksi YouTube API

In [ ]:
from google.colab import userdata
from googleapiclient.discovery import build

API_KEY = userdata.get("YOUTUBE_API_KEY")

youtube = build(
    "youtube",
    "v3",
    developerKey=API_KEY
)

print("API Connected")

API Connected

In [ ]:
request = youtube.videos().list(
    part="snippet",
    chart="mostPopular",
    regionCode="ID",
    maxResults=1
)

response = request.execute()

print("YouTube API request successful")
print("Video title:", response["items"][0]["snippet"]["title"])

YouTube API request successful
Video title: Dermaga Terakhir Di Hatimu

## 4. Validasi API

### Tujuan

Memastikan API dapat digunakan sebelum proses scraping dilakukan.

## 5. Menentukan Kata Kunci Pencarian

###Tujuan
Mengumpulkan video yang berkaitan dengan Infrastruktur transportasi modern seperti Kereta Cepat Whoosh, MRT Jakarta, dan LRT Jabodebek. Keyword dipilih berdasarkan kata-kata yang populer.

In [ ]:
request = youtube.search().list(
    q="kereta cepat whoosh",
    part="snippet",
    maxResults=5,
    type="video"
)

response = request.execute()

print("Jumlah video:", len(response["items"]))

Jumlah video: 5

## Menentukan Kata Kunci

In [ ]:
video_ids = []

keywords = [

    # Whoosh
    "kereta cepat jakarta bandung",
    "kereta cepat whoosh",
    "review whoosh",
    "naik whoosh",

    # MRT
    "mrt jakarta",
    "review mrt jakarta",
    "naik mrt jakarta",
    "pengalaman mrt jakarta",

    # LRT
    "lrt jabodebek",
    "review lrt jabodebek",
    "naik lrt jabodebek",
    "pengalaman lrt jabodebek"

]

keywords.extend([

    "kereta cepat indonesia",

    "kereta cepat whoosh terbaru",

    "whoosh cnbc",

    "whoosh kompas tv",

    "mrt jakarta terbaru",

    "lrt jabodebek terbaru",

    "review kereta cepat",

    "pengalaman naik whoosh"

])

##6. Mengumpulkan Daftar Video

###Tujuan
Mengambil video yang relevan berdasarkan kata kunci yang telah ditentukan.

In [ ]:
video_ids = []

for keyword in keywords:

    print("Keyword:", keyword)

    request = youtube.search().list(
        q=keyword,
        part="snippet",
        maxResults=10,
        type="video"
    )

    response = request.execute()

    for item in response["items"]:

        if "videoId" in item["id"]:

            video_ids.append(
                item["id"]["videoId"]
            )

video_ids = list(set(video_ids))

print("Jumlah video unik:", len(video_ids))

Keyword: kereta cepat jakarta bandung
Keyword: kereta cepat whoosh
Keyword: review whoosh
Keyword: naik whoosh
Keyword: mrt jakarta
Keyword: review mrt jakarta
Keyword: naik mrt jakarta
Keyword: pengalaman mrt jakarta
Keyword: lrt jabodebek
Keyword: review lrt jabodebek
Keyword: naik lrt jabodebek
Keyword: pengalaman lrt jabodebek
Keyword: kereta cepat indonesia
Keyword: kereta cepat whoosh terbaru
Keyword: whoosh cnbc
Keyword: whoosh kompas tv
Keyword: mrt jakarta terbaru
Keyword: lrt jabodebek terbaru
Keyword: review kereta cepat
Keyword: pengalaman naik whoosh
Jumlah video unik: 153

## 7. Scraping Komentar dan Evaluasi Hasil Scraping
###Tujuan

Mengambil komentar dari seluruh video yang berhasil dikumpulkan. Komentar inilah yang nantinya akan digunakan sebagai dataset analisis sentimen. Memastikan jumlah komentar telah memenuhi kebutuhan dataset dan sesuai dengan ketentuan submission.

In [ ]:
import pandas as pd
import numpy as np

comments = []

from tqdm import tqdm

for video_id in tqdm(video_ids):

    try:

        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100
        )

        response = request.execute()

        while True:

            for item in response["items"]:

                comment = item[
                    "snippet"
                ]["topLevelComment"][
                    "snippet"
                ]["textDisplay"]

                comments.append(comment)

            if "nextPageToken" in response:

                request = youtube.commentThreads().list(
                    part="snippet",
                    videoId=video_id,
                    maxResults=100,
                    pageToken=response["nextPageToken"]
                )

                response = request.execute()

            else:
                break

    except:
        pass

print(
    "Jumlah komentar:",
    len(comments)
)

  8%|▊         | 12/153 [00:03<00:20,  6.75it/s]WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"
 72%|███████▏  | 110/153 [00:21<00:02, 16.00it/s]WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"
 89%|████████▉ | 136/153 [00:24<00:02,  8.25it/s]WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"
100%|██████████| 153/153 [00:27<00:00,  5.63it/s]

Jumlah komentar: 32712

## 8. Membentuk Dataset

###Tujuan
Mengubah seluruh komentar menjadi DataFrame agar bisa dianalisis. Dataset hasil scraping akan disimpan dalam bentuk DataFrame dengan satu kolom yaitu "Comment" yang berisi komentar pengguna YouTube terkait Infrastruktur transportasi modern seperti Kereta Cepat Whoosh, MRT Jakarta, dan LRT Jabodebek.

In [ ]:
import pandas as pd

df = pd.DataFrame(
    comments,
    columns=["comment"]
)

print(df.shape)

df.head()

(32712, 1)

                                             comment
0  Dana MBG 235 trilyun setahun. Itu lebih dari c...
1                   Gak jalan 😂 sama kayak hambalang
2  Ahy mendukung wosh sama saja membunuh menguran...
3  Kemampuan menteri dan era kepemimpinan sekaran...
4  Ga bakal jadi klo AHY yg urus infrastruktur. D...

##9. Data Understanding
### Tujuan
Melihat kualitas data hasil scraping. Tahap ini dilakukan untuk:
1. Memastikan tidak ada nilai kosong
2. Mengetahui tipe data
3. Memastikan seluruh komentar berhasil tersimpan

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32712 entries, 0 to 32711
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   comment  32712 non-null  object
dtypes: object(1)
memory usage: 255.7+ KB

In [ ]:
df.isnull().sum()

comment    0
dtype: int64

##10. Menghapus Duplikasi & Filtering Komentar Tidak Informatif
###Tujuan
Menghilangkan komentar yang sama agar model tidak bias.

Tahap ini juga bertujuan menghapus komentar yang terlalu pendek atau terlalu panjang sehingga tidak memberikan informasi sentimen yang memadai.

Komentar yang terdiri dari emoji, simbol, atau hanya satu kata umumnya tidak memberikan konteks yang cukup untuk proses analisis sentimen.

In [ ]:
df = df.drop_duplicates()

print(df.shape)

(32004, 1)

In [ ]:
df["comment_length"] = df["comment"].astype(str).apply(len)

df["comment_length"].describe()

count    32004.00000
mean        99.06068
std        195.95278
min          1.00000
25%         31.00000
50%         59.00000
75%        112.00000
max      10420.00000
Name: comment_length, dtype: float64

### Insight

Proses filtering panjang komentar berhasil mengurangi data yang tidak informatif tanpa menghilangkan sebagian besar dataset.

Jumlah komentar berkurang dari 32.712 menjadi 32.004 komentar, atau hanya sekitar 2,16% dari total data. Hal ini menunjukkan bahwa mayoritas komentar yang berhasil dikumpulkan memiliki panjang yang cukup untuk merepresentasikan opini atau sentimen pengguna.

Dataset hasil filtering dinilai memiliki kualitas yang lebih baik karena telah mengurangi komentar berupa emoji, simbol, singkatan yang terlalu pendek, maupun komentar yang sangat panjang dan berpotensi mengandung noise.

##11. Simpan Dataset Mentah
###Tujuan
Menyimpan hasil scraping sebagai backup apabila quota API habis atau runtime Colab ter-reset.

In [ ]:
df.to_csv(
    "dataset_transportasi_raw.csv",
    index=False
)

print("Dataset berhasil disimpan.")

Dataset berhasil disimpan.

In [ ]:
### END OF SCRAPING ###